package TrafficTicket;

import javax.swing.JFrame;


public class ResetPassword extends JFrame {
   // Variables declaration - do not modify
  private javax.swing.JTextField NPassword;
  private javax.swing.JTextField NPassword2;
  private javax.swing.JButton Save;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private JFrame frame;
  private javax.swing.JPanel panel;
  // End of variables declaration

  /**
   * Creates new form ResetPassword
   */
  public ResetPassword() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
 
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents() {
    frame = new JFrame();
    frame.setSize(500, 500);
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    NPassword = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    Save = new javax.swing.JButton();
    NPassword2 = new javax.swing.JTextField();
    panel = new javax.swing.JPanel();

    setBackground(new java.awt.Color(255, 255, 255));

    jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel1.setText("Reset Password");

    jLabel2.setText("New Password:");

    jLabel3.setText("Confirm Password:");

    Save.setText("Save");
    Save.setBorder(
        javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(242, 242, 242), java.awt.Color.lightGray));
    Save.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        SaveActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(panel);
    panel.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209,
                            javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 192,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 83,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 192,
                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(59, Short.MAX_VALUE)));
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NPassword, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(NPassword2, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(Save)
                .addGap(38, 38, 38)));

              frame.getContentPane().add(panel);
              frame.setVisible(true);
  }// </editor-fold>

  private void SaveActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
    Person p = new Person();
    if (NPassword2.getText().equals(NPassword.getText())) {
      p.setPassword(NPassword2.getText());
      setVisible(false);;
    }

  }

 
}
